### ISSUE TITLE
[Bug] Generating a report with --reporter-htmlextra-hideResponse results in an error

### ISSUE THREAD

**Issue by Christopher-Kane** [DannyDainton/newman-reporter-htmlextra#257]
**Describe The Problem**
There is a microservice at my work that allows a user to download a PDF agreement. While experimenting with different CLI options for newman-reporter-htmlextra I found "--reporter-htmlextra-hideResponse".  When I went to use "--reporter-htmlextra-hideResponse" on a request who response data is the raw PDF output, it failed with the following stacktrace:

`C:\Users\christopher.kane\.jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs_14.5\node_modules\newman-reporter-htmlextra\lib\index.js:125
            list = list.toLowerCase()
                        ^
TypeError: list.toLowerCase is not a function
    at Object.<anonymous> (C:\Users\christopher.kane\.jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs_14.5\node_modules\newman-reporter-htmlextra\lib\index.js:125:25)
    at Object.wrapper (C:\Users\christopher.kane\.jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs_14.5\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\internal\wrapHelper.js:15:19)
    at eval (eval at createFunctionContext (C:\Users\christopher.kane\.jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs_14.5\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:262:23), <anonymous>:10:134)
    at Object.prog [as inverse] (C:\Users\christopher.kane\.jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs_14.5\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\runtime.js:268:12)
    at Object.<anonymous> (C:\Users\christopher.kane\.jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs_14.5\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\helpers\if.js:27:22)
    at Object.<anonymous> (C:\Users\christopher.kane\.jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs_14.5\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\helpers\if.js:37:35)
    at Object.wrapper (C:\Users\christopher.kane\.jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs_14.5\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\internal\wrapHelper.js:15:19)
    at eval (eval at createFunctionContext (C:\Users\christopher.kane\.jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs_14.5\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:262:23), <anonymous>:59:51)
    at prog (C:\Users\christopher.kane\.jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs_14.5\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\runtime.js:268:12)
    at execIteration (C:\Users\christopher.kane\.jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs_14.5\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\helpers\each.js:51:19)
    at Object.<anonymous> (C:\Users\christopher.kane\.jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs_14.5\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\helpers\each.js:61:13)
    at Object.wrapper (C:\Users\christopher.kane\.jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs_14.5\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\internal\wrapHelper.js:15:19)
    at eval (eval at createFunctionContext (C:\Users\christopher.kane\.jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs_14.5\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:262:23), <anonymous>:11:49)
    at prog (C:\Users\christopher.kane\.jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs_14.5\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\runtime.js:268:12)
    at Object.invokePartial (C:\Users\christopher.kane\.jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs_14.5\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\runtime.js:334:12)
    at Object.invokePartialWrapper [as invokePartial] (C:\Users\christopher.kane\.jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs_14.5\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\runtime.js:84:39)`

**Steps To Reproduce**
Not sure if this is reproducible without a service that returns raw PDF data. But if it does essentially any report attempted to be generated while also passing in "--reporter-htmlextra-hideResponse" will result in the above error.

This is the command I was running that generated the error:
`newman run 'Write_Responses_To_FileCopy.postman_collection.json' \
    -e 'apps-qa-env.postman_environment.json' \
    -r cli,htmlextra,slack \
    --reporter-htmlextra-export 'newman/Dynamic Agreement Service Automation Report.html' \
    --reporter-htmlextra-hideResponse \
    --reporter-htmlextra-darkTheme`

**What Are You Seeing**
I am seeing an error occur when generating the report when there should be no error. Removing "--reporter-htmlextra-hideResponse" results in a successfully generated report.

**Collection and Environment Files**
I cannot give you a collection or environment file, everything is internal and would not work.

**Version and Platform Information:**
 - `newman` Version 5.0.1
 - `newman-reporter-htmlextra` Package Version 1.17.4
 - OS Windows 10

**Additional Context**
Add any other context about the problem not mentioned, the more information that can be provided the better. 

- Are you using the reporter from the command line or with a script? 
Using it from Git Bash
- Are you using the default template or a custom version?
Default template
- If you are using a custom `.hbs` file, please include this on the report.
No custom .hbs file.
- Have you made any local changes to the `index.js` file?
Nope.

**Comment by DannyDainton** [comment]
Hey @Christopher-Kane

Thanks for reporting that - let me have a little look to see what's going on there.

I know what the error means but I need to get a request sorted that will return a raw PDF...any way that you can help there. It can be a dummy test site. 😁

**Comment by Christopher-Kane** [comment]
So I will say that I'm the Software Test Engineer for this service and not the Software Engineer who made the service =P.

But with that being said, I think you could create a simple nodeJS server with an endpoint that when hit could just return raw PDF data. I can give the raw PDF data that I'm using at work, and then all the nodeJS server would need to do is just return that data to you.. I think.

**Comment by DannyDainton** [comment]
Let me see where I get and reach out if I need some more info 😁

**Comment by DannyDainton** [comment]
So one thing you could try, that flag needs a `request name` passed into it so it knows _which_ response to hide:

```
newman run collection.json -r htmlextra --reporter-htmlextra-hideResponse "Auth Request"
```

There are flags that are `true/false` so you wouldn't need to pass anything but that one needs one.

**Comment by Christopher-Kane** [comment]
Oh, you know I'm not sure if I realized it worked like that. Thank you!

I didn't actually need that flag, I was experimenting with it at the time because we were having trouble generating the same report elsewhere and we thought it was a response size issue and didn't realize it needed to have a name of a request passed. 

Let me try that and see what happens.

**Comment by Christopher-Kane** [comment]
Dang, so yeah if you don't include a request name it results in that error. If you do include a request name it does exactly as it's supposed to. So this is definitely my fault :joy:

**Comment by Christopher-Kane** [comment]
Gotta love when you're searching for the person who shot you in the foot, and then you realize you were the one holding the gun the entire time.

**Comment by DannyDainton** [comment]
It's on both of us... :)

If nothing is passed, it should fall back to a state like it's not even been used...if that makes sense. 😄

**Comment by DannyDainton** [comment]
I'm going to leave this as an open bug for now and take a better look at what's going on for that command - Thanks for highlighting it 🏆

**Comment by Christopher-Kane** [comment]
Of course! I appreciate you taking a look at it. Let me know if there is anything you need from me 😄

**Comment by DannyDainton** [comment]
So I think I have a fix for this - It looks like it's doing the right thing and my tests are still passing but it's getting late and I need to take another look in the morning. 😄

**Comment by Christopher-Kane** [comment]
No worries dude! I appreciate your responsiveness on this. Since I realized that flag was causing the issue, I removed it since I didn't need it but hopefully if someone else uses that flag and doesn't read everything like me, at least they won't be scratching their head as to why it's now failing 😅

**Comment by DannyDainton** [comment]
To be fair, it's a slightly bigger problem than just that as the same internal function is used in different flags - If you were to use another flag that takes an argument but you don't add one...it'll error. 

You've actually done me a favour 😄

**Comment by Christopher-Kane** [comment]
Oooohhhh, I honestly think that is what one of the devs I work with was trying to say earlier today but I didn't understand what he meant by "there's like only 10 that call this function". Okay that makes a lot of sense now, well I'm glad it was actually of benefit to you, I was hoping I didn't waste too much of your time.

**Comment by DannyDainton** [comment]
Never wasting anyone's time - I'm just happy that people are using the reporter ❤️

**Comment by DannyDainton** [comment]
@Christopher-Kane I think I fixed it on the new version 🤞

**Comment by Christopher-Kane** [comment]
You're the best Danny, thanks again 😄.

**Comment by Christopher-Kane** [comment]
Whenever that's available to test out, let me know and I'd be more than happy to do it 😄 .

**Comment by DannyDainton** [comment]
Should be there now if you update the package to 1.18.0 😁

**Comment by Christopher-Kane** [comment]
Ah I tried to update and then npm complained, woops 😅. Just updated and if no parameter is given, it will still successfully generate the report! Thanks again Danny!
