### ISSUE TITLE
[BUG] Running API test on Azure Devops MS hosted agent machine throwing error 'TypeError: Cannot convert object to primitive value'

### ISSUE THREAD

**Issue by pankajdevrani** [DannyDainton/newman-reporter-htmlextra#316]
Executing newman API test with htmlextrea report throwing an error 'Cannot convert object to primitive value' in Azure devops MS hosted agent machines.

**What Are You Seeing**

2021-05-06T12:12:43.1564660Z C:\npm\prefix\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\utils.js:91
2021-05-06T12:12:43.1572380Z     string = '' + string;
2021-05-06T12:12:43.1573433Z                 ^
2021-05-06T12:12:43.1573723Z 
2021-05-06T12:12:43.1574109Z TypeError: Cannot convert object to primitive value
2021-05-06T12:12:43.1574789Z     at Object.escapeExpression (C:\npm\prefix\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\utils.js:91:17)
2021-05-06T12:12:43.1576037Z     at eval (eval at createFunctionContext (C:\npm\prefix\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:262:23), <anonymous>:3:20)
2021-05-06T12:12:43.1582865Z     at prog (C:\npm\prefix\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\runtime.js:268:12)
2021-05-06T12:12:43.1585571Z     at execIteration (C:\npm\prefix\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\helpers\each.js:51:19)
2021-05-06T12:12:43.1586961Z     at Object.<anonymous> (C:\npm\prefix\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\helpers\each.js:61:13)
2021-05-06T12:12:43.1589602Z     at Object.wrapper (C:\npm\prefix\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\internal\wrapHelper.js:15:19)
2021-05-06T12:12:43.1590835Z     at eval (eval at createFunctionContext (C:\npm\prefix\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:262:23), <anonymous>:11:49)
2021-05-06T12:12:43.1592818Z     at prog (C:\npm\prefix\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\runtime.js:268:12)
2021-05-06T12:12:43.1594966Z     at execIteration (C:\npm\prefix\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\helpers\each.js:51:19)
2021-05-06T12:12:43.1597164Z     at Object.<anonymous> (C:\npm\prefix\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\helpers\each.js:61:13)
2021-05-06T12:12:43.1600674Z     at Object.wrapper (C:\npm\prefix\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\internal\wrapHelper.js:15:19)
2021-05-06T12:12:43.1601696Z     at eval (eval at createFunctionContext (C:\npm\prefix\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:262:23), <anonymous>:11:49)
2021-05-06T12:12:43.1602603Z     at Object.prog [as fn] (C:\npm\prefix\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\runtime.js:268:12)
2021-05-06T12:12:43.1603409Z     at Object.<anonymous> (C:\npm\prefix\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\helpers\if.js:29:22)
2021-05-06T12:12:43.1604196Z     at Object.wrapper (C:\npm\prefix\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\internal\wrapHelper.js:15:19)
2021-05-06T12:12:43.1605305Z     at eval (eval at createFunctionContext (C:\npm\prefix\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:262:23), <anonymous>:64:47)
2021-05-06T12:12:43.2805167Z ##[error]Cmd.exe exited with code '1'.
2021-05-06T12:12:43.3156413Z ##[section]Finishing: CL Script : Run Postman Collection and Create CLI, JUNIT and HTML Report

**Steps To Reproduce The Issue**

In azure devops, add task to npm task to install newman, html-extra. Then add CLI task to run the newman command.

![image](https://user-images.githubusercontent.com/65667028/117914992-f7e12a00-b301-11eb-9311-e719f1516577.png)

**Screenshots and Gifs**
![image](https://user-images.githubusercontent.com/65667028/117914671-6d002f80-b301-11eb-88b0-c4c8b3fad6ef.png)

**Collection and Environment Files**
I will not be able to share collection and evnvironment file. But it it was working earlier and now it is not woking.

Any files that would allow me to reproduce the issue locally...
The issue it not occurring locally.

**Version and Platform Information:**
 - `newman` versions tried :-5.1.2, 5.2.3
 - `newman-reporter-htmlextra` 1.20.4
 - OS : Windows server 2018 with VS 2019 installed. https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md

 - **The CLI command you've used to start Newman** : newman run https://api.getpostman.com/collections/$(CoreAPICollection)?apikey=$(PostmanAPIKey) --environment https://api.getpostman.com/environments/$(PostmanStagingEnvName)?apikey=$(PostmanAPIKey) -g $(System.DefaultWorkingDirectory)/_CartisAPITesting/drop/Postman_Globals_Variables.json --global-var authToken=$(PostmanAuthToken) --insecure --timeout 900000 --timeout-request 120000 --timeout-script 1000000 -r cli,junit,htmlextra --reporter-htmlextra-title "API Tests" --reporter-htmlextra-browserTitle "API Tests" --reporter-htmlextra-titleSize 1 --reporter-htmlextra-timezone Asia/Calcutta --reporter-htmlextra-logs true --reporter-htmlextra-skipHeaders Authorization --reporter-htmlextra-export Results%TestResultHtmlFileName% --reporter-junit-export $(TestResultXmlFileName)

**Additional Context**

I tried with several version combination of html extra and newman to make it work but it is failing inconsistently

**Comment by DannyDainton** [comment]
I've never used Azure or have the ability to replicate that issue locally.

Are you able to run the same command outside of that platform?

Not really sure what I can do here to be honest. 🤔

**Comment by DannyDainton** [comment]
I see that you have the logs flag, from the CLI this is true when used so you can remove the extra `true` in the command

**Comment by DannyDainton** [comment]
There isn't anything I can do here that I can think of - if it's working locally like you mentioned, it points to it being an issue with Azure and not specifically the reporter.

Going to close this out but if you provide more context and details I can look to open it again.

**Comment by pankajdevrani** [comment]
> Are you able to run the same command outside of that platform?
Yes, locally it works fine.
> I see that you have the logs flag, from the CLI this is true when used so you can remove the extra `true` in the command

That did not seem to help(I tried.)

> it being an issue with Azure and not specifically the reporter.
I think you are right in that regard, what was interesting to me was that, when installing htmlextra reporter it is giving a warning saying 'newman-reporter-htmlextra@1.20.4 requires a peer of newman@^5.1.2 but none is installed' but I already installed the newman in the step before installing html-extra.
`2021-05-06T12:11:18.6512693Z > node -e "try{require('./postinstall')}catch(e){}"
2021-05-06T12:11:18.6514813Z npm WARN newman-reporter-htmlextra@1.20.4 requires a peer of newman@^5.1.2 but none is installed. You must install peer dependencies yourself.
2021-05-06T12:11:18.6515103Z `
I don't know why it is happening inconsistently. 
I thought maybe you would be able to help me in this regard, I knew it is not something to do with html-extra reporter particularly but thought maybe you know something which would help me so I raised a bug. Sorry if I wasted your time. Let me know if you have something which might help me resolve this issue(Currently I think it has to do with versioning combination of html-extra reporter, newman and npm).

**Comment by pankajdevrani** [comment]
@DannyDainton Can you tell me what do you understand from this error message which I am getting, 
`C:\Program Files\nodejs\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\utils.js:91
2021-05-21T10:42:48.1986772Z     string = '' + string;
2021-05-21T10:42:48.1987298Z                 ^
2021-05-21T10:42:48.1987665Z 
2021-05-21T10:42:48.1988249Z TypeError: Cannot convert object to primitive value`

I install the azure agent in my machine and ran the same command and I am still getting this error message. I dont get this error message when I runt he command manually from my machine(without using agent machine)

**Comment by DannyDainton** [comment]
I don't know what that error is or what it refers to. 

It's coming from here `\node_modules\handlebars\dist\cjs\handlebars\utils.js:91` which isn't something that I wrote :D 

As you mentioned, you don't get this when running the command locally so there are not really many things that I can suggest 🤔

**Comment by pankajdevrani** [comment]
> I see that you have the logs flag, from the CLI this is true when used so you can remove the extra `true` in the command

Hey Danny, Sorry to bother you again, I think I found the issue, before explaining it I would like to know what you meant by 'from the CLI this is true when used' ?

**Comment by DannyDainton** [comment]
When you use this ` --reporter-htmlextra-logs` it's setting that to `true` so the extra `true` part here is redundant ` --reporter-htmlextra-logs true`. That might be interpreted by Azure as something else or a different command.

You would only need to use `true` if you were using Newman and the reporter as a library:

```
const newman = require('newman');

newman.run({
    collection: './pathToFile/collection.json', // Collection URL from a public link or the Postman API can also be used
    reporters: ['htmlextra'],
    reporter: {
        htmlextra: {
            logs: true
        }
    }
});
```

**Comment by pankajdevrani** [comment]
@DannyDainton Yes, you suggested this earlier(removing the unnecessary true) but I thought you meant something else.
Anyway, currently when we run a newman cli command with `--reporter-htmlextra-logs true`(which is redundant, as you mentioned) from CLI, it throws the above error I have mentioned,
`2021-05-21T10:42:48.1986772Z string = '' + string;`
`2021-05-21T10:42:48.1988249Z TypeError: Cannot convert object to primitive value`

I have verified in two different windows machine, both locally and using azure agent.
Should this be raised as a bug?

**Comment by DannyDainton** [comment]
What's the bug? It doesn't work like that. 

There's no mention that I know of in my docs that said that do that. You just did that :D 

There's nothing to fix. :D
