### ISSUE TITLE
Collapse Folder Group and Request 

### ISSUE THREAD

**Issue by RuggeriLuca** [DannyDainton/newman-reporter-htmlextra#4]
it will be nice if in Request tab the 
Folders headers and the Requests header will be collapse

**Comment by DannyDainton** [comment]
I might look into this but I can't give any promises to changing the default reporter.

There is an 'alternative' template in the repo that has something similar to what you want but the style of the report is completely different. 

These are just templates and can be changed on your side by creating a new one that works for you and allows you to change the areas that you.

You can then use the `-reporter-htmlextra-template` flag to reference your own file.

**Comment by DannyDainton** [comment]
@RuggeriLuca I've updated the default template on version 1.40.1 to include the collapsible requests.

The images of what these look like can be found in the README file.

**Comment by RuggeriLuca** [comment]
Hi , Thank you . 
i have replace the report into the folder 
and now i take the below error :
`
C:\TEMP>newman run  https://www.getpostman.com/collections/9a018b27426520fb7f72 --folder "Draw Operations V3.0" -e "UAT-L10-DrawOperation.postman_environment.json" -g "MyWorkspace.postman_globals.json" -k -r htmlextra --reporter-html-export c:\temp\myreport3.html
newman: Newman v4 deprecates support for the v1 collection format
  Use the Postman Native app to export collections in the v2 format

C:\Users\l.ruggeri\AppData\Roaming\npm\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:267
            throw new Error(str);
            ^

Error: Parse error on line 1105:
...pan class="pl-c1">{{</span><span class="
-----------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
    at Parser.parseError (C:\Users\l.ruggeri\AppData\Roaming\npm\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:267:19)
    at Parser.parse (C:\Users\l.ruggeri\AppData\Roaming\npm\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:336:30)
    at HandlebarsEnvironment.parse (C:\Users\l.ruggeri\AppData\Roaming\npm\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\compiler\base.js:46:43)
    at compileInput (C:\Users\l.ruggeri\AppData\Roaming\npm\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:515:19)
    at ret (C:\Users\l.ruggeri\AppData\Roaming\npm\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:524:18)
    at EventEmitter.<anonymous> (C:\Users\l.ruggeri\AppData\Roaming\npm\node_modules\newman-reporter-htmlextra\lib\index.js:221:22)
    at EventEmitter.emit (C:\Users\l.ruggeri\AppData\Roaming\npm\node_modules\newman\node_modules\eventemitter3\index.js:203:33)
    at done (C:\Users\l.ruggeri\AppData\Roaming\npm\node_modules\newman\lib\run\index.js:277:29)
    at C:\Users\l.ruggeri\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\backpack\index.js:56:34
    at PostmanCollectionRun._process (C:\Users\l.ruggeri\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\run.js:161:13)
    at PostmanCollectionRun.<anonymous> (C:\Users\l.ruggeri\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\run.js:166:76)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)`

**Comment by RuggeriLuca** [comment]
Nice Thank you 

I will try to make also the folder collapsible

**Comment by RuggeriLuca** [comment]
I will made teh Folder Collapsible are you intrested ?

**Comment by DannyDainton** [comment]
It's already included in the latest version.

**Comment by DannyDainton** [comment]
@RuggeriLuca This has be updated in the default and dark theme dashboard views - The new version is published and is part of version 1.50.1.
